-- 코드를 입력하세요
select date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, ifnull(USER_ID, NULL) as USER_ID, SALES_AMOUNT
from(
SELECT  PRODUCT_ID, USER_ID, SALES_AMOUNT, SALES_DATE
from ONLINE_SALE 
union
SELECT  PRODUCT_ID, NULL as USER_ID , SALES_AMOUNT, SALES_DATE
from OFFLINE_SALE  
) a
where SALES_DATE between '2022-03-01' and '2022-03-31'
order by SALES_DATE, PRODUCT_ID, USER_ID